name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * # 8:00 AM daily
    - cron : 00 14 * * * # 7:30 PM daily
    - cron : 00 06 * * 1-5 # 11:30 am IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Node.js and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22
      - name: Install Newman and Html-extra globally
        run: | 
             npm install -g newman 
             npm install -g newman-reporter-htmlextra
      - name: Run the Postman collection with newman
        run: |
             newman run 'Inwarranty Flow Collection Copy 2.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testDataCreateJob.csv \
             -r cli,htmlextra
             
